### ISSUE TITLE
Fixes for your branch part 1

### ISSUE THREAD

**Issue by tjcocklin** [SCCapstone/CognitoFormsDev#101]
https://github.com/SCCapstone/CognitoFormsDev/blob/dc54ddca7b033b80015261e7f827ea5fbae24e7e/cognito_form/lambda/us-east-1_cognito-skill/index.js#L19

Change above to:

 APP_ID= undefined;

**Comment by tjcocklin** [comment]
Don't forget to close your branches inside your git commit messages (e.g. git commit -m "closes #101")

**Comment by kblock97** [comment]
closes #101
