### ISSUE TITLE
Fixes to your branch part 2

### ISSUE THREAD

**Issue by tjcocklin** [SCCapstone/CognitoFormsDev#102]
https://github.com/SCCapstone/CognitoFormsDev/blob/dc54ddca7b033b80015261e7f827ea5fbae24e7e/cognito_form/lambda/us-east-1_cognito-skill/index.js#L265

Change to:

static InsertFunctionName(obj,path,def) {

The type of function declaration you used throws an error inside the helper class.

**Comment by kblock97** [comment]
closes #102
