### ISSUE TITLE
Fixes to your branch part 3

### ISSUE THREAD

**Issue by tjcocklin** [SCCapstone/CognitoFormsDev#103]
https://github.com/SCCapstone/CognitoFormsDev/blob/dc54ddca7b033b80015261e7f827ea5fbae24e7e/cognito_form/lambda/us-east-1_cognito-skill/index.js#L432

Your messing an argument here. The correct form is:

this.emit(':askWithCard', speechOutput, repromptSpeech, cardTitle, cardContent, imageObj);

**Comment by kblock97** [comment]
closes #103
