### ISSUE TITLE
Amazon echo dots for testing

### ISSUE THREAD

**Issue by tjcocklin** [SCCapstone/CognitoFormsDev#110]
@josemvidal I have deposited two Amazon echo dots in your mailbox, installed with the Alexa skill for your TAs and teamMuseumKiosk.

**Comment by josemvidal** [comment]
@SCCapstone/teammuseumkiosk it is actually much easier to test this app by login into developer.amazon.com as they explain the Release Notes. This way, you can take screenshots, type instead of talk, and view the Display.

**Comment by tjcocklin** [comment]
@josemvidal, I need to pick up, the two Amazon echo dots, if could you leave them with the secretaries again that would be a great help.

**Comment by josemvidal** [comment]
I left one with the secretaries for you to pickup.

@SunCherry has the other one. Can you leave yours with the secretaries also?

**Comment by tjcocklin** [comment]
@josemvidal  @SunCherry Picked up one of the echo dots from the secretary today, just need the last one.

**Comment by tjcocklin** [comment]
@SunCherry , just got your message. Which lab are you in?

**Comment by tjcocklin** [comment]
Second Amazon echo retrieved.
