### ISSUE TITLE
The Display is never updated

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CognitoFormsDev#112]
From my testing, the display is never updated, after the first screen with the form names.

![Alexa Developer Console 2019-04-09 17-04-12](https://user-images.githubusercontent.com/228704/55835203-8ebad700-5ae9-11e9-940e-1e623dbaef83.jpg)

**Comment by tjcocklin** [comment]
Hello, we've also taken notice of this and have found that Alexa output from the Test simulator, doesn't always match that which is displayed by the Alexa App. For example we found  similar issues in a built in Alexa weather skill. See below:

Visual output to Test simulator:

![image](https://user-images.githubusercontent.com/23157098/55847343-e7549900-5b16-11e9-8e36-262b29f120aa.png)

Visual output to the Alexa app:

![image](https://user-images.githubusercontent.com/23157098/55847437-3c90aa80-5b17-11e9-9df1-dbd0bff762ca.png)

We are unable to apply a fix to this aberration, as its outside the scope of our project. We will add a note in the testing instructions about this.

**Comment by josemvidal** [comment]
Yes, but the bug is that there is only one screen. Did you implement other screens? If so, give instructions on how to get to them.

**Comment by tjcocklin** [comment]
If I understand correctly you are referring to different visual cards. The visual cards are accessible from the Alexa.amazon.com, or through the Alexa app. For example:

![image](https://user-images.githubusercontent.com/23157098/55897812-46ee8b00-5b8f-11e9-8b0f-2f46ea7129a9.png)

After loading form multichoice you'll see:

![image](https://user-images.githubusercontent.com/23157098/55897895-769d9300-5b8f-11e9-9e12-1e562000d873.png)

After giving the start command you'll see:

![image](https://user-images.githubusercontent.com/23157098/55897984-a5b40480-5b8f-11e9-9816-cc96cc84d4c9.png)

**Comment by tjcocklin** [comment]
Testing instructions on the wiki have been updated to suggest usage of the Alexa.amazon.com, or the device's Alexa app to view visual cards.

**Comment by tjcocklin** [comment]
The aforementioned changes should fix the issue close #112
