### ISSUE TITLE
Does not like "five fifty"

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CognitoFormsDev#115]
![Alexa Developer Console 2019-04-09 17-11-13](https://user-images.githubusercontent.com/228704/55835719-94fd8300-5aea-11e9-941c-a04acf44f52f.jpg)

**Comment by tjcocklin** [comment]
The input "five fifty" is ambiguous and can be interpreted to mean five dollars and fifty cents, or five hundred and fifty dollars.

The above example translates it to $550. For the sake of clarity the skill will be updated display the amount that was given deemed, outside the range.

That said, given that there are existing means to express your desired input (e.g. $5.50, or five dollars and fifty cents), we must therefore decline your suggestion to make "five fifty" a valid argument as it may inject further ambiguity in how to interpret the users input.

Thank you for bringing this to our attention.
