### ISSUE TITLE
Currency does not like forty cents

### ISSUE THREAD

**Issue by macsc97** [SCCapstone/CognitoFormsDev#122]
Upon answering the first question about gas prices with "forty cents" all I get is a beep and then Alexa tells me what "forty cents" means if I respond again. 

![forty cents](https://user-images.githubusercontent.com/23297831/56389672-1f836800-61f8-11e9-86ba-df93ed49018e.PNG)
![forty cents 2](https://user-images.githubusercontent.com/23297831/56389675-2316ef00-61f8-11e9-9b33-6d09b8360589.PNG)

**Comment by macsc97** [comment]
Upon further attempts, saying something else like "ten" without the "answer" before it does similar. But saying something random like "test" asks again correctly. 

![forty cents 3](https://user-images.githubusercontent.com/23297831/56395275-f79c0080-6207-11e9-99d6-7817405c8aa3.PNG)

**Comment by tjcocklin** [comment]
Thank you for your input. This behavior is known and not something that can be fixed. The issues lies with Alexa's interaction model which requires a keyword (e.g. answer) before a free form response. For responses outside of the expected model, a FallbackIntent is suppose to be triggered. 

Unfortunately the implementation and use of this FallbackIntent appears inconsistent. See issue #116, for more details.
