### ISSUE TITLE
Cannot access skill when user submits form

### ISSUE THREAD

**Issue by lcarrnix** [SCCapstone/CognitoFormsDev#126]
<img width="408" alt="Screen Shot 2019-04-12 at 11 20 55 AM" src="https://user-images.githubusercontent.com/22942080/56472998-74f78900-6433-11e9-9d06-e5c699489760.png">
when submitting the multichoice form, I received an error that Alexa couldn't access the form

**Comment by lcarrnix** [comment]
Similar bug when submitting the Name form after repeating answers. 
<img width="397" alt="Screen Shot 2019-04-21 at 1 32 38 PM" src="https://user-images.githubusercontent.com/22942080/56473493-01a54580-643a-11e9-9413-fce67c9e4fec.png">

**Comment by tjcocklin** [comment]
Thank you for your input, this particular error message isn't coded into the Cognito RC1 skill. I suspect that there may have been a problem accessing the AWS server where the  Alexa skill is hosted. Unfortunately that's beyond our purview as developers, and thus can not be fixed by us.

**Comment by tjcocklin** [comment]
Issue can not be resolved.
