### ISSUE TITLE
Printing a . before instructions.

### ISSUE THREAD

**Issue by lcarrnix** [SCCapstone/CognitoFormsDev#128]
Sometimes if I just type nonsense, it will respond with ". Say start..". Not sure why it's printing an extra dot at the beginning but it looks odd.

<img width="393" alt="Screen Shot 2019-04-21 at 1 11 33 PM" src="https://user-images.githubusercontent.com/22942080/56473299-2c41cf00-6437-11e9-850e-f39eac7f664c.png">

**Comment by kblock97** [comment]
Closed issue #128
