### ISSUE TITLE
Form jumped to next question

### ISSUE THREAD

**Issue by lcarrnix** [SCCapstone/CognitoFormsDev#131]
<img width="412" alt="Screen Shot 2019-04-21 at 1 35 12 PM" src="https://user-images.githubusercontent.com/22942080/56473522-5ea0fb80-643a-11e9-9bd1-85d771da82ab.png">
After saying an incorrect answer, form prompted me again correctly. But when I then said 'yes' instead of an appropriate response, it jumped to the next question instead of prompting me again.

**Comment by lcarrnix** [comment]
<img width="403" alt="Screen Shot 2019-04-21 at 1 37 27 PM" src="https://user-images.githubusercontent.com/22942080/56473543-a162d380-643a-11e9-9c13-074eff70ce5b.png">
Did it again with next question.

**Comment by lcarrnix** [comment]
It's not saving the responses even as it jumps to next question, if that helps. It just repeated my responses from the 'Name' form I completed earlier. 
<img width="395" alt="Screen Shot 2019-04-21 at 1 39 14 PM" src="https://user-images.githubusercontent.com/22942080/56473560-03bbd400-643b-11e9-950d-e9b1f64bd91c.png">

**Comment by tjcocklin** [comment]
You have to say "answer" followed by your response.
